" Cody M. Jones' personal vim configuration
"
" Copyright (C) 2019 Cody M. Jones <codymjones@pm.me>
"
" This program is free software: you can redistribute it and/or modify
" it under the terms of the GNU General Public License as published by
" the Free Software Foundation, either version 3 of the License, or
" (at your option) any later version.
"
" This program is distributed in the hope that it will be useful,
" but WITHOUT ANY WARRANTY; without even the implied warranty of
" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
" GNU General Public License for more details.
"
" You should have received a copy of the GNU General Public License
" along with this program.  If not, see <https://www.gnu.org/licenses/>.

" Enable filetype plugins
filetype plugin on

filetype indent on

" Map Escape to Caps Lock upon entering Vim
au VimEnter * silent! !xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

" Reverse mapping upon exiting Vim
au VimLeave * silent! !xmodmap -e 'clear Lock' -e 'keycode 0x42 = Caps_Lock'

" Keycode delay
set timeoutlen=1000
set ttimeoutlen=5

" Always show current position
set ruler

" Show column 80
set colorcolumn=80

" Limit text width in mutt to 72 chars
au BufRead /tmp/mutt-* set tw=72

" Wrap text at column 80
set textwidth=80

" Show line numbers
set number
set relativenumber

" Highlight current line
set cursorline

" Ignore case when searching
set ignorecase
set smartcase

" Highlight search results
set hlsearch

" Show matching {[()]}
set showmatch

" No sound on errors
set noerrorbells
set novisualbell

" Enable syntax highlighting
syntax enable

colorscheme gruvbox
set background=dark

" Set utf8 as standard encoding and en_US as standard language
set encoding=utf8

" Always show the status line even with one window
set laststatus=2

set expandtab
set tabstop=4
set shiftwidth=4
