" Cody M. Jones' personal vim configuration
"
" Copyright (C) 2019 Cody M. Jones <codymjones@pm.me>
"
" This program is free software: you can redistribute it and/or modify
" it under the terms of the GNU General Public License as published by
" the Free Software Foundation, either version 3 of the License, or
" (at your option) any later version.
"
" This program is distributed in the hope that it will be useful,
" but WITHOUT ANY WARRANTY; without even the implied warranty of
" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
" GNU General Public License for more details.
"
" You should have received a copy of the GNU General Public License
" along with this program.  If not, see <https://www.gnu.org/licenses/>.

" Enable filetype plugins
filetype plugin on

filetype indent on

let g:airline_theme='gruvbox'

" Always show current position
set ruler

" Show column 80
set colorcolumn=80

" Limit text width in mutt to 72 chars
au BufRead /tmp/mutt-* set tw=72

" Wrap text at column 80
"set textwidth=80

" Show line numbers
set number

" Highlight current line
set cursorline

" Ignore case when searching
set ignorecase

" Highlight search results
set hlsearch

" Show matching {[()]}
set showmatch

" No sound on errors
set noerrorbells
set novisualbell

" Enable syntax highlighting
syntax enable

set background=dark

colorscheme gruvbox

" Set utf8 as standard encoding and en_US as standard language
set encoding=utf8

" Always show the status line
" set laststatus=2

set expandtab
set tabstop=4
set shiftwidth=4
